version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=rsforumvue
      - MYSQL_PASSWORD=
    ports:
      - "3306:3306"
  php:
    container_name: website_img
    build:
      context: ./
    ports:
      - "80:80"
    volumes:
      - ./server:/var/www/html
    depends_on:
      - mysql